version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - root/mongodb-data:/data/db
    ports:
      - 27019:27017
    networks:
      - mern-app  

  web:
    build: ./web
    container_name: ui_web
    command: bash -c "
        mvn spring-boot:run"
    ports: 
      - 8080:8080
    networks:
      - mern-app   
    depends_on:
      - mongodb 

  frontend:
    build: ./app
    container_name: ui_server
    stdin_open: true
    command: sh -c "
        npm start"
    ports:
      - 3000:3000
    networks:
      - mern-app   
    depends_on:
      - web
networks: 
  mern-app:
  driver: bridge      
volumes:
  scrum-data:
    driver: local      


       

   
