version: "3"
services:
  frontend:
    image: sasender/app:v2
    container_name: react
    command: sh -c "
        npm start"
        
    stdin_open: true
    ports:
      - "3000:3000"
    links:
      - mongodb
  springboot:
    image: sasender/web:v3
    container_name: springboot
    command: bash -c "
        mvn spring-boot:run"
    ports:
      - "8080:8080"
    links:
      - mongodb

  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    container_name: mongodb
    ports:
      - "27017:27017"