version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
    - /home/ubuntu/data/mongo:/data/db
    ports:
      - 27019:27019

  web:
    build: ./web
    container_name: ui_web
    ports: 
      - 8080:8080
    links:
      - mongo  

  frontend:
    build: ./app
    container_name: ui_server
    ports:
      - 3000:3000
    links:
      - ui_web
volumes:
  scrum-data:      


       

   
