version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    volumes:
    - /home/ubuntu/data/mongo:/data/db
    ports:
      - 27017:27018

  web:
    build: ./web
    container_name: ui_web
    command: bash -c "
        mvn spring-boot:run"
    ports: 
      - 8080:8080
    links:
      - mongodb 

  frontend:
    build: ./app
    container_name: ui_server
    stdin_open: true
    command: sh -c "
        npm start"
    ports:
      - 3000:3000
    links:
      - web
volumes:
  scrum-data:      


       

   
