version: "3"
services:
  frontend:
    image: sasender/app:v2
    container_name: react
    command: sh -c "
        npm start"
        
    stdin_open: true
    ports:
      - "3000:3000"

  springboot:
    image: sasender/web:v3
    container_name: springboot
    command: bash -c "
        mvn spring-boot:run"
    ports:
    - "8080:8080"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - "27019:27017"